# Build Stage
FROM node:22-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS build
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm --filter payment-orchestrator prisma generate
RUN pnpm --filter payment-orchestrator build

# Production Stage
FROM base AS production
WORKDIR /usr/src/app
COPY --from=build /usr/src/app/node_modules /usr/src/app/node_modules
COPY --from=build /usr/src/app/apps/payment-orchestrator/dist /usr/src/app/apps/payment-orchestrator/dist
COPY --from=build /usr/src/app/apps/payment-orchestrator/package.json /usr/src/app/apps/payment-orchestrator/package.json
COPY --from=build /usr/src/app/apps/payment-orchestrator/prisma /usr/src/app/apps/payment-orchestrator/prisma
COPY --from=build /usr/src/app/apps/payment-orchestrator/src/generated-client /usr/src/app/apps/payment-orchestrator/src/generated-client

EXPOSE 3000
CMD [ "node", "apps/payment-orchestrator/dist/main" ]
